/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.TelefoneCliente;
import Resources.Formatar;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Toolkit;
import java.net.URL;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Douglas Horvath
 */
public class NovoCliente_SelecionaTelefones extends javax.swing.JDialog {

    private ArrayList<TelefoneCliente> telefones;
    private DefaultTableModel modeloTelefones;
    /**
     * Creates new form SelecionaTelefonesPaciente
     * @param parent Janela Pai
     * @param modal TRUE para modal e FALSE para não modal
     */
    public NovoCliente_SelecionaTelefones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        URL url = this.getClass().getResource("/Imagens/windowThumb.png");
        java.awt.Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        
        //Configurações da tabela de Telefones
        modeloTelefones = (DefaultTableModel)tbTelefones.getModel();
        modeloTelefones.setNumRows(0);
        tbTelefones.getColumnModel().getColumn(0).setPreferredWidth(300);
        tbTelefones.getColumnModel().getColumn(1).setPreferredWidth(700);
        JTableHeader cabecalhoCadastrados = tbTelefones.getTableHeader();  
        cabecalhoCadastrados.setFont(new Font("Arial", Font.BOLD, 14)); 
    }
    
    public void preenxeTabelaTelefones()
    {
        modeloTelefones.setNumRows(0);
        String[] linha = new String[2];
        if(telefones != null)
        {
            for(int i=0; i<telefones.size(); i++)
            {
                linha[0] = telefones.get(i).getTipo();
                if("FIXO".equals(linha[0]))
                {
                    linha[1] = Formatar.format("(##) ####-####", telefones.get(i).getTelefone());
                }
                if("MOVEL".equals(linha[0]))
                {
                    linha[1] = Formatar.format("(##) #####-####", telefones.get(i).getTelefone());
                }
                modeloTelefones.addRow(linha);
            }
        }
    }

    public ArrayList<TelefoneCliente> getTelefones() {
        return telefones;
    }

    public void setTelefones(ArrayList<TelefoneCliente> telefones) {
        this.telefones = telefones;
        if(this.telefones == null)
        {
            this.telefones = new ArrayList<>();
        }
        preenxeTabelaTelefones();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTelefones = new javax.swing.JTable();
        brNovoFixo = new javax.swing.JButton();
        btNovoCelular = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btNovoCelular1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panelFundo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setText("Telefones Pessoa");

        tbTelefones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo", "Telefone"
            }
        ));
        tbTelefones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbTelefones);

        brNovoFixo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        brNovoFixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fixoMicroIcon.png"))); // NOI18N
        brNovoFixo.setText("Novo Fixo");
        brNovoFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brNovoFixoActionPerformed(evt);
            }
        });

        btNovoCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNovoCelular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/celularMicroIcon.png"))); // NOI18N
        btNovoCelular.setText("Novo Celular");
        btNovoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoCelularActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saveMicroIcon.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelMicroIcon.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btNovoCelular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btNovoCelular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/trashMicroIcon.png"))); // NOI18N
        btNovoCelular1.setText("Apagar");
        btNovoCelular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoCelular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brNovoFixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNovoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNovoCelular1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(brNovoFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNovoCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNovoCelular1)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(391, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brNovoFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brNovoFixoActionPerformed
        NovoCliente_SelecionaTelefones_NovoTelefone n = new NovoCliente_SelecionaTelefones_NovoTelefone((Frame)this.getParent(), true);
        try {
            n.setFixo();
        } catch (ParseException ex) {
            Logger.getLogger(NovoCliente_SelecionaTelefones.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setVisible(true);
        if(n.getTelefone() != null)
        {
            this.telefones.add(n.getTelefone());
        }
        preenxeTabelaTelefones();
    }//GEN-LAST:event_brNovoFixoActionPerformed

    private void btNovoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoCelularActionPerformed
        NovoCliente_SelecionaTelefones_NovoTelefone n = new NovoCliente_SelecionaTelefones_NovoTelefone((Frame)this.getParent(), true);
        try {
            n.setCelular();
        } catch (ParseException ex) {
            Logger.getLogger(NovoCliente_SelecionaTelefones.class.getName()).log(Level.SEVERE, null, ex);
        }
        n.setVisible(true);
        if(n.getTelefone() != null)
        {
            this.telefones.add(n.getTelefone());
        }
        preenxeTabelaTelefones();
    }//GEN-LAST:event_btNovoCelularActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        commit();
        this.dispose();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.telefones = null;
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btNovoCelular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoCelular1ActionPerformed
        int row = tbTelefones.getSelectedRow();
        if(row > -1)
        {
            modeloTelefones.removeRow(row);
            commit();
        }
    }//GEN-LAST:event_btNovoCelular1ActionPerformed

    private void commit()
    {
        this.telefones = new ArrayList<>();
        TelefoneCliente t;
        for(int i=0; i<tbTelefones.getRowCount();i++)
        {
            t = new TelefoneCliente();
            String s = (String)tbTelefones.getValueAt(i, 1);
            s = s.replace(" ", "").replace("-", "").replace("(", "").replace(")", "");
            t.setTelefone(s);
            t.setTipo((String)tbTelefones.getValueAt(i, 0));
            this.telefones.add(t);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brNovoFixo;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovoCelular;
    private javax.swing.JButton btNovoCelular1;
    private javax.swing.JButton btSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JTable tbTelefones;
    // End of variables declaration//GEN-END:variables
}
