/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.Cliente;
import Classes.TelefoneCliente;
import Resources.Alert;
import Resources.Patterns;
import Resources.Verificar;
import com.github.gilbertotorrezan.viacep.se.ViaCEPClient;
import com.github.gilbertotorrezan.viacep.shared.ViaCEPEndereco;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.AbstractAction;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Douglas Horvath
 */
public class NovoCliente extends javax.swing.JInternalFrame {

    private MouseListener[] listenersBkp;
    private String ComponentName = "NOVO_PACIENTE";
    private ArrayList<TelefoneCliente> telefones;
    private Cliente cliente = null;
    private boolean cadastrado = false;
    private boolean okdata = true;
    
    
    public NovoCliente() {
        initComponents();
        //ImageIcon icon = new ImageIcon(ClassLoader.getSystemResource("Imagens/cliente_16.png"));
        //this.setFrameIcon(icon);
        cbEstado.removeAllItems();
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RS", "SC", "SE", "SP", "TO" })); 
        this.telefones = new ArrayList<>();
        tfIdade.setEditable(false);
        
        btSalvar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_DOWN_MASK), "evento");
        btSalvar.getActionMap().put("evento", new AbstractAction(){
         @Override
            public void actionPerformed(ActionEvent e){
               btSalvar.doClick();
            }
        });
        
        btCancelar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_W, InputEvent.CTRL_DOWN_MASK), "evento");
        btCancelar.getActionMap().put("evento", new AbstractAction(){
         @Override
            public void actionPerformed(ActionEvent e){
               btCancelar.doClick();
            }
        });
        
    }
    
    public void locale(Dimension desktopSize)
    {
        String[] locate = Preferences.userRoot().get(ComponentName, "-100,-100").split(",");
        System.out.println("locate : "+locate[0]+","+locate[1]);
//        locate[0] = "-100";
//        locate[1] = "-100";
        int x = Integer.parseInt(locate[0]);
        int y = Integer.parseInt(locate[1]);
        if(x == -100)
        {
            Dimension jInternalFrameSize = this.getSize();
            x = (desktopSize.width - jInternalFrameSize.width)/2;
            y = (desktopSize.height- jInternalFrameSize.height)/2;
            System.out.println("x = "+x+", y ="+y);
            this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
            btPin.setSelected(false);
            Icon pinIcon = new ImageIcon(getClass().getClassLoader().getResource("Imagens/pinMicroBlack16.png"));
            btPin.setIcon(pinIcon);
        }
        else
        {
            System.out.println("recuperando ultima localização");
            btPin.setSelected(true);
            Icon pinIcon = new ImageIcon(getClass().getClassLoader().getResource("Imagens/pinMicroRed16.png"));
            btPin.setIcon(pinIcon);
            this.setLocation(x, y);
            listenersBkp = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().getMouseListeners();
            for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().getMouseListeners()){
                ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().removeMouseListener(listener);
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        lbPaciente10 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        tfIdade = new javax.swing.JFormattedTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        btTelefones = new javax.swing.JButton();
        lbSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        lbDataNascimento = new javax.swing.JLabel();
        lbRG = new javax.swing.JLabel();
        tfRG = new javax.swing.JFormattedTextField();
        lbEstadoCivil = new javax.swing.JLabel();
        cbEstadoCivil = new javax.swing.JComboBox();
        lbProfissao = new javax.swing.JLabel();
        tfProfissao = new javax.swing.JTextField();
        lbCOD1 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        panelFundo2 = new javax.swing.JPanel();
        tfNumero = new javax.swing.JFormattedTextField();
        tfCep = new javax.swing.JFormattedTextField();
        lbRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        lbCEP = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox();
        lbCidade = new javax.swing.JLabel();
        btPesquisarCEP = new javax.swing.JButton();
        btPin = new javax.swing.JToggleButton();
        dateChooserDataNascimento = new com.toedter.calendar.JDateChooser();

        panelFundo.setBackground(new java.awt.Color(204, 204, 204));
        panelFundo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitulo.setText("Nova Pessoa");

        lbNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNome.setText("Nome");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCPF.setText("CPF");

        lbPaciente10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPaciente10.setText("*");

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saveMicroIcon.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelMicroIcon.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        tfIdade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfIdade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btTelefones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTelefones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/telefoneMicroIcon.png"))); // NOI18N
        btTelefones.setText("Telefones");
        btTelefones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelefonesActionPerformed(evt);
            }
        });

        lbSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbSexo.setText("Sexo");

        cbSexo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        lbDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDataNascimento.setText("Data de Nascimento");

        lbRG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRG.setText("RG");

        try {
            tfRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfRG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstadoCivil.setText("Estado Civil");

        cbEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Viuvo(a)" }));

        lbProfissao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbProfissao.setText("Profissão");

        tfProfissao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        lbCOD1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCOD1.setText("Idade");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEmail.setText("Email");

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        panelFundo2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados de Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tfNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNumeroKeyReleased(evt);
            }
        });

        try {
            tfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCepKeyReleased(evt);
            }
        });

        lbRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRua.setText("Rua");

        tfRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNumero.setText("Nº");

        lbBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBairro.setText("Bairro");

        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbCEP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCEP.setText("CEP");

        tfCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEstado.setText("Estado");

        cbEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCidade.setText("Cidade");

        btPesquisarCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        btPesquisarCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFundo2Layout = new javax.swing.GroupLayout(panelFundo2);
        panelFundo2.setLayout(panelFundo2Layout);
        panelFundo2Layout.setHorizontalGroup(
            panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundo2Layout.createSequentialGroup()
                        .addComponent(lbCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbRua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundo2Layout.createSequentialGroup()
                        .addComponent(lbBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumero)))
                .addContainerGap())
        );
        panelFundo2Layout.setVerticalGroup(
            panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbRua)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCEP))
                    .addComponent(btPesquisarCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBairro)
                    .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNumero))
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCidade))
                    .addGroup(panelFundo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEstado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pinMicroBlack16.png"))); // NOI18N
        btPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPinActionPerformed(evt);
            }
        });

        dateChooserDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbCPF)
                        .addGap(4, 4, 4)
                        .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbDataNascimento)
                        .addGap(10, 10, 10)
                        .addComponent(dateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCOD1)
                        .addGap(4, 4, 4)
                        .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbRG)
                        .addGap(10, 10, 10)
                        .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbSexo)
                        .addGap(4, 4, 4)
                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbProfissao)
                        .addGap(4, 4, 4)
                        .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lbEmail)
                        .addGap(11, 11, 11)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFundoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286)
                                .addComponent(btTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFundoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPaciente10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(panelFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTitulo)
                            .addComponent(btTelefones))
                        .addGap(8, 8, 8)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbPaciente10))
                            .addGroup(panelFundoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lbNome)))
                        .addGap(8, 8, 8)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFundoLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCPF)
                                    .addComponent(lbDataNascimento)
                                    .addComponent(lbCOD1)))
                            .addComponent(dateChooserDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFundoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRG)
                                    .addComponent(lbEstadoCivil)
                                    .addComponent(lbSexo))))
                        .addGap(6, 6, 6)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFundoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbProfissao)
                                    .addComponent(lbEmail))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelFundo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancelar)
                            .addComponent(btSalvar)))
                    .addComponent(btPin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(tfNome.getText().isEmpty())
        {
            Alert.alert("Insira um nome válido!", 1000, Color.BLACK, Color.WHITE,null,new Dimension(300,50));
            tfNome.requestFocus();
            tfNome.selectAll();
        }
        else
        {
            String cpf = null;
            Date dataC = dateChooserDataNascimento.getDate();
            LocalDate dataNascimento;
            
            if(dataC != null)
            {
                dataNascimento = dateChooserDataNascimento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            }
            else
            {
                dataNascimento=null;
            }
            String aux = tfCPF.getText().replace(".", "").replace("-", "").replace(" ", "");
            if(!aux.isEmpty())
            {
                if(Verificar.verificaCpf(aux))
                {
                    cpf = aux;
                }
            }
            else
            {
                cpf = null;
            }
            if(cpf != null || dataNascimento != null)
            {
                if(Cliente.getCliente(cpf) != null)
                {
                    Alert.alert("CPF existente", 1000, Color.BLACK, Color.WHITE,null,new Dimension(300,50));
                    tfCPF.requestFocus();
                    tfCPF.selectAll();
                }
                else
                {
                    if(Cliente.getCliente(tfNome.getText().toUpperCase(),dataNascimento) != null && cpf == null)
                    {
                        Alert.alert("Paciente com Nome e Data Nascimento conflitante, inserir CPF", 1000, Color.BLACK, Color.WHITE,null,new Dimension(450,50));
                        tfCPF.requestFocus();
                        tfCPF.selectAll();
                    }
                    else{
                        boolean validEmail;
                        System.out.println("email: "+tfEmail.getText());
                        if(tfEmail.getText() == null || tfEmail.getText().trim().isEmpty())
                        {
                            validEmail = true;
                        }
                        else{
                            if(Verificar.validEmail(tfEmail.getText()))
                            {
                                validEmail = true;
                            }
                            else
                            {
                                validEmail = false;
                                Alert.alert("Email Inválido", 1000, Color.BLACK, Color.WHITE,null,new Dimension(250,50));
                                tfEmail.requestFocus();
                                tfEmail.selectAll();
                            }
                        }
                        if(validEmail)
                        {
                            System.out.println(cpf);
                            int numero = -1;
                            if(!tfNumero.getText().isEmpty())
                            {
                                numero = Integer.parseInt(tfNumero.getText());
                                numero = Math.abs(numero);
                            }

                            Cliente p = new Cliente();
                            p.setNome(tfNome.getText());
                            p.setCpf(cpf);

                            p.setDataNascimento(dataNascimento);
                            p.setRg(tfRG.getText().replace(".", "").replace("-", "").replace(" ", ""));
                            p.setEstadoCivil(cbEstadoCivil.getSelectedItem().toString());
                            p.setSexo(cbSexo.getSelectedItem().toString());
                            p.setProfissao(tfProfissao.getText());
                            p.setEmail(tfEmail.getText());
                            p.setRua(tfRua.getText());
                            p.setNumero(numero);
                            p.setBairro(tfBairro.getText());
                            p.setCep(tfCep.getText().replace("-", ""));
                            p.setCidade(tfCidade.getText());
                            p.setEstado(cbEstado.getSelectedItem().toString());
                            p.setTelefones(telefones);
                            if(p.insert())
                            {
                                this.cadastrado = true;
                                this.cliente = p;
                                Alert.alert("Pessoa cadastrado com sucesso!", 1000, Color.BLACK, Color.WHITE,null,new Dimension(350,50));
                                this.dispose();
                            }
                            else
                            {
                                this.cadastrado = false;
                                this.cliente = null;
                                Alert.alert("Erro ao cadastrar Pessoa", 3000, Color.BLACK, Color.WHITE,null,new Dimension(300,50));
                            }
                        }
                    }
                }
            }
            else
            {
                if(okdata)
                {
                    Alert.alert("CPF ou Data Nascimento Obrigatório", 2000, Color.BLACK, Color.WHITE,null,new Dimension(300,50));
                    tfCPF.requestFocus();
                    tfCPF.selectAll();
                }
            }

        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void fechar() {
        
        this.dispose();
    }
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btTelefonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelefonesActionPerformed
        NovoCliente_SelecionaTelefones npst = new NovoCliente_SelecionaTelefones(null, true);
        npst.setTelefones(telefones);
        npst.setVisible(true);
        if(npst.getTelefones() != null)
        this.telefones = npst.getTelefones();
    }//GEN-LAST:event_btTelefonesActionPerformed

    private void dateChooserDataNascimentoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserDataNascimentoPropertyChange
        if(dateChooserDataNascimento.getDate() != null)
        {
            LocalDate data = dateChooserDataNascimento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate hoje = LocalDate.now();
            Period dif = Period.between(data, hoje);
            tfIdade.setText(String.valueOf(dif.getYears()));
            tfIdade.setToolTipText(dif.getYears()+" anos, "+dif.getMonths()+" meses e "+dif.getDays()+" dias");
        }
        else{
            tfIdade.setText("");
            tfIdade.setToolTipText("");
        }
    }//GEN-LAST:event_dateChooserDataNascimentoPropertyChange

    private void tfCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCepKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            pesquisarCEP();
        }
    }//GEN-LAST:event_tfCepKeyReleased
  
    private void pesquisarCEP()
    {
        String cep = tfCep.getText();
        if(cep != null)
        {
            cep = cep.replace("-", "");
            System.out.println("CEP: "+cep);
            ViaCEPClient viacep = new ViaCEPClient();
            ViaCEPEndereco endereco;
            try {
                endereco = viacep.getEndereco(cep);
                if(endereco != null)
                {
                    tfRua.setText(endereco.getLogradouro());
                    tfBairro.setText(endereco.getBairro());
                    tfCidade.setText(endereco.getLocalidade());
                    cbEstado.setSelectedItem(endereco.getUf());
                    tfNumero.requestFocus();
                }
            } catch (IOException ex) {
                Logger.getLogger(NovoCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             
        }
    }
    
    private void btPesquisarCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCEPActionPerformed
        pesquisarCEP();
    }//GEN-LAST:event_btPesquisarCEPActionPerformed

    private void btPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPinActionPerformed
        if(btPin.isSelected())
        {
            Icon pinIcon = new ImageIcon(getClass().getClassLoader().getResource("Imagens/pinMicroRed16.png"));
            btPin.setIcon(pinIcon);
            Dimension dim = new Dimension((int)this.getLocation().getX(),(int)this.getLocation().getY());
            Preferences.userRoot().put(ComponentName, (int)dim.getWidth()+","+(int)dim.getHeight());
            listenersBkp = ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().getMouseListeners();
            for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().getMouseListeners()){
                ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().removeMouseListener(listener);
            }
            System.out.println("preferences: "+Preferences.userRoot().get(ComponentName, "-100,-100"));
        }
        else
        {
            for(MouseListener listener : listenersBkp)
            {
                ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).getNorthPane().addMouseListener(listener);
            }
            Preferences.userRoot().put(ComponentName, "-100,-100");
            Icon pinIcon = new ImageIcon(getClass().getClassLoader().getResource("Imagens/pinMicroBlack16.png"));
            btPin.setIcon(pinIcon);
        }
    }//GEN-LAST:event_btPinActionPerformed

    private void tfNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btSalvar.doClick();
        }
    }//GEN-LAST:event_tfNumeroKeyReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btPesquisarCEP;
    private javax.swing.JToggleButton btPin;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btTelefones;
    private javax.swing.JComboBox cbEstado;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbSexo;
    private com.toedter.calendar.JDateChooser dateChooserDataNascimento;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCEP;
    private javax.swing.JLabel lbCOD1;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoCivil;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbPaciente10;
    private javax.swing.JLabel lbProfissao;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JPanel panelFundo2;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JFormattedTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JFormattedTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfNumero;
    private javax.swing.JTextField tfProfissao;
    private javax.swing.JFormattedTextField tfRG;
    private javax.swing.JTextField tfRua;
    // End of variables declaration//GEN-END:variables
}
